### PR TITLE
Keep dropdown-menu and internal text-field focused when opening

### LINKED ISSUE #54: It’s difficult to apply the same styles for the element for `focused` and `opened` states
As the internal vaadin-text-field has the focused styles (after #53 is possibly fixed), it would be great to use the same styles also when the dropdown is open, as the field is still semantically focused. 

It is the same with vaadin-combo-box – you have the dropdown visible and can navigate the list with the arrow keys while the main host element is still focused.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #54

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/61)

### CODE REVIEW

**Comment by web-padawan** [comment]
Tests are failing in Chrome 60 but not in Firefox. Will continue to investigate.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/61#-:-Kz4EA-QxiyAieF_EA_u:b43i9zy)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-dropdown-menu.html, line 138 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/61#-Kz5PUWy3jwNC1rBHT9C:-Kz5PUWy3jwNC1rBHT9D:b-ix6oop) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/5b3d833983d19db1e8ad209ca02e21cf02febc89/vaadin-dropdown-menu.html#L138)):*
> ```HTML
>           super.ready();
>         }
>       }
> ```

I see this a bit hacky to understand, I would prefer to override the `_setFocused()` in the component,  so as it considers whether the  menu is opened.

```
  _setFocused(focused) {
    super._setFocused(this.opened || focused);
    this.focusElement._setFocused(this.focused);
  }
```

---

*[test/dropdown-menu-test.html, line 392 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/61#-Kz5PrSeFafT2gdMtrZ6:-Kz5PrSeFafT2gdMtrZ7:bh7nvbd) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/5b3d833983d19db1e8ad209ca02e21cf02febc89/test/dropdown-menu-test.html#L392)):*
> ```HTML
>             expect(dropdown.opened).to.be.true;
>             expect(dropdown.focused).to.be.true;
>             expect(input.focused).to.be.true;
> ```

you need to assert that dropdown also is focused not only the input

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/61)*

**Comment by web-padawan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-dropdown-menu.html, line 138 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/61#-Kz5PUWy3jwNC1rBHT9C:-Kz5drV-JQ3ZyawxoH9F:b-hom2qa) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/5b3d833983d19db1e8ad209ca02e21cf02febc89/vaadin-dropdown-menu.html#L138)):*
>  Keep dropdown-menu and internal text-field focused when opening
Thank you for the suggestion, it looks much better. I haven't realized how `super` could be useful for cases like this before. Done.

---

*[test/dropdown-menu-test.html, line 392 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/61#-Kz5PrSeFafT2gdMtrZ6:-Kz5eTeXW8TQTUYJmvoT:bfhbaq6) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/5b3d833983d19db1e8ad209ca02e21cf02febc89/test/dropdown-menu-test.html#L392)):*
> before
there is an assertion in the line above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/61)*

**Comment by manolo** [comment]
Fixed the test, because opening the overlay imperatively does not mean that the input has focus, so we need to focus it programatically before. Also you need to check tests in a similar env than in travis, and means that you have to maintain the focus in a separated window. I Normally do it by focusing the debug console or a  different tab.

:lgtm_strong: 

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/61#-:-Kz7ZxP9jyFKohCXeniI:bocm03i)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/61)*

**Pull request merged**
