### PR TITLE
Add slot for selected content

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/vaadin-core/issues/136

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/7)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-dropdown-menu.html, line 376 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/7#-KxRq8jGCgnN_8ceuFCw:-KxRq8jGCgnN_8ceuFCx:b-n1slb9) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/aebb81501fe53408bc076b13db491bf14cc11cac/vaadin-dropdown-menu.html#L376)):*
> ```HTML
>             }
> 
>             this._slotted.slot = 'selected';
> ```

Should we define the "slotted" element in `<vaadin-dropdown-menu>` template as a light dom child for the `<vaadin-dropdown-menu-text-field>`so we could skip a lot of this logic (storing the slotted element, generating the div, programmatically setting slot="selected")?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/7)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown-menu.html, line 376 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/7#-KxRq8jGCgnN_8ceuFCw:-KxS-JFOIHhAJaXsdIAn:b-xdurra) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/aebb81501fe53408bc076b13db491bf14cc11cac/vaadin-dropdown-menu.html#L376)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should we define the "slotted" element in `<vaadin-dropdown-menu>` template as a light dom child for the `<vaadin-dropdown-menu-text-field>`so we could skip a lot of this logic (storing the slotted element, generating the div, programmatically setting slot="selected")?
</blockquote></details>

Much better, Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/7)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 134 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/7#-KxS6GEgY6v3dY2es0Ip:-KxS6GEgY6v3dY2es0Iq:bd62fln) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/f925649c497f309f8d6c648a7993e85923bc0979/vaadin-dropdown-menu.html#L134)):*
> ```HTML
> 
>     <vaadin-dropdown-menu-text-field label="[[label]]" readonly value="[[value]]">
>       <slot name="prefix" slot="prefix"></slot>
> ```

Why only prefix? Should we also expose suffix also?

---

*[vaadin-dropdown-menu.html, line 375 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/7#-KxS64gxIT4UIViD2U1y:-KxS64gxIT4UIViD2U1z:b-kgdcwk) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/f925649c497f309f8d6c648a7993e85923bc0979/vaadin-dropdown-menu.html#L375)):*
> ```HTML
>               this._selectionElement.textContent = selected.getAttribute('label');
>             } else {
>               const clon = selected.cloneNode(true);
> ```

clon -> clone? Not a blocker

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/7#-:-KxS6UppUt9_qPgtIMIV:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[vaadin-dropdown-menu.html, line 375 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/7#-KxS64gxIT4UIViD2U1y:-KxS8K_Rz9IFw_z4gwdN:biwk4ha) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/f925649c497f309f8d6c648a7993e85923bc0979/vaadin-dropdown-menu.html#L375)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

clon -> clone? Not a blocker
</blockquote></details>

Yep, that's Spanish. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/7)*

**Pull request merged**
