### PR TITLE
Update the styling example

### PR DESCRIPTION
**Pull request by limonte**
Connected to https://github.com/vaadin/components-team-tasks/issues/347

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/119)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[demo/dropdown-menu-basic-demos.html, line 128 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/119#-LAYGL83BSqnfrud0T27:-LAYGL83BSqnfrud0T28:bsn7j7r) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/95111bb6b81bc31d857a06398b125414619f9e6f/demo/dropdown-menu-basic-demos.html#L128)):*
> ```HTML
>       <template preserve-content>
>         <style>
>           vaadin-item:hover {
> ```

Couple of issues about the styles used in this demo:
1. Too much style changes in the hover style block. The disappearing borders an italic font makes the whole demo look jumpy.
2. You really notice any changes to the styles if you use mouse. Navigating with keyboard you hardly notice any difference to the default styles.

Suggestion: Let's keep the changes minimal and so that they're visible for everyone. For example: Just set the font-style italic fo all vaadin-items.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/119)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/dropdown-menu-basic-demos.html, line 128 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/119#-LAYGL83BSqnfrud0T27:-LAYNyCL5gTS56jVHqUg:be6ejlx) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/95111bb6b81bc31d857a06398b125414619f9e6f/demo/dropdown-menu-basic-demos.html#L128)):*
> Suggestion: Let's keep the changes minimal and so that they're visible for everyone. For example: Just set the font-style italic fo all vaadin-items.

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/119)*

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/119)*

**Comment by tomivirkki** [comment]
*[demo/dropdown-menu-basic-demos.html, line 128 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/119#-LAYGL83BSqnfrud0T27:-LAlbrMp-8XCfthCxqU6:b-88ieh7) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/95111bb6b81bc31d857a06398b125414619f9e6f/demo/dropdown-menu-basic-demos.html#L128)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> Suggestion: Let's keep the changes minimal and so that they're visible for everyone. For example: Just set the font-style italic fo all vaadin-items.

Done.
</blockquote></details>

Not done. It still has those weird hover styles.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/119)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/119)*

**Pull request merged**
