### PR TITLE
Use container element as focusable. 

### LINKED ISSUE #23: Broken touch device behavior
Since there’s a readonly input which gets focused on tap, the viewport zooms in on that input making the overlay be misaligned. They input also shows that the value has a lot of extra white space characters after the actual value.

vaadin-dropdown-menu-iphone

### PR DESCRIPTION
**Pull request by manolo**
Move css conditions to style block.
Fixes #23

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/26)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/26#-:-Kxrr3HF9lXFpuv9-l9z:bnfp4nl)*

**Comment by manolo** [comment]
It's still not the best approach. will close this in order not be merged to master

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/26#-:-KxsbLuIcdkIj2Y_uv5S:bhg8nmo)*

**Comment by manolo** [comment]
Fixed now, disabling the native input is the easiest way to avoid iOS zooming. Ready for review again

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/26#-:-KxsoKr1-8N9u_M2uu2L:bqm832o)*

**Comment by YuriyVaadin** [comment]
It will be awesome If we can find a way to set disabled in static template. Probably we should consider setting min font-size to 16px. Not a blocker.

:lgtm: 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/26#-:-KxvgN56_BbA6IKZ9Kq7:b-i8brlu)*

**Comment by Toshegg** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/26#-:-Kxw0SVxTZzaDr90fyJi:bnfp4nl)*

**Pull request merged**
