### PR TITLE
Wrap native input in a slot, use slot assignment to toggle

### LINKED ISSUE #56: Remove native text input from `vaadin-dropdown-menu-text-field`
The element is currently hidden using `visiblity: hidden;`. That causes problems with the text-field default styles which apply flex for that part, making it take space in the layout even though invisible, and not allowing the `slot=selected` to take all of the available space.

How I see it, we should just remove the native `<input part="value">` from the `vaadin-dropdown-menu-text-field` template (or hide it explicitly with `display: none;`), and apply the “value” part for the selected slot instead: `<div slot="selected" part="value"></div>`.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #56

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/65)

### CODE REVIEW

**Comment by manolo** [comment]
There is one broken test

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/65#-:-Kz5AS6iyHwq-LrdIpf-:br900xa)*

**Comment by manolo** [comment]
Rebased with master

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/65#-:-Kz7dNBlBLRTN3JRCWZ9:bo3smbb)*

**Comment by manolo** [comment]
:lgtm_strong:  good approach!

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/65#-:-Kz7eUXuRnhO_3WLijPy:ben246b)*

**Comment by jouni** [comment]
This is a step in the right direction, but it actually didn’t solve the issue of having to duplicate the styles for `part="value"`. Those styles are applied in the shadow DOM scope of `vaadin-dropdown-menu-text-field` and the `<div part="value" slot="value">` is in the light DOM scope 🙁

**Comment by jouni** [comment]
I don’t know if there’s any good way to avoid the duplication of styles, but just wanted to point that out, that currently I have to copy the styles for `part="value"` from `vaadin-text-field` to `vaadin-dropdown-menu`

**Comment by platosha** [comment]
@jouni what about doing something like:

```css
[part="value"],
::slotted([part="value"]) {
  /* unduplicated styles */
}
```

**Comment by jouni** [comment]
@platosha, thanks! That’s a nice workaround :+1:

**Pull request merged**
