### PR TITLE
Fix tabIndex by extending control-state. Fixes #14

### LINKED ISSUE #14: `tabIndex` does not work
Setting tabindex does not work as expected.
We should extend `vaadin-control-state-mixin` like we do in combo-box.

Tested with this example:
```
<vaadin-dropdown-menu tabindex="4" label="TabIndex 4"></vaadin-dropdown-menu>
<vaadin-dropdown-menu tabindex="3" label="TabIndex 3"></vaadin-dropdown-menu>
<vaadin-dropdown-menu tabindex="2" disabled label="TabIndex 2 disabled"></vaadin-dropdown-menu>
<vaadin-dropdown-menu tabindex="1" label="TabIndex 1"></vaadin-dropdown-menu>
```

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/19)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 45 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19#-KxphhfGvK4J1ofEzwx9:-KxphhfGvK4J1ofEzwxA:b-58zzi1) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9bcab2e23ee3f54f0f036ad7b231c46f5f05ee2c/vaadin-dropdown-menu.html#L45)):*
> ```HTML
> </dom-module>
> 
>

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 45 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19#-KxphhfGvK4J1ofEzwx9:-Kxqyy_X9B0ywjh06Cmt:big2dqx) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9bcab2e23ee3f54f0f036ad7b231c46f5f05ee2c/vaadin-dropdown-menu.html#L45)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

wtf is this?
</blockquote></details>

pushed by accident, was part of other thing I was playing with. 
Done.

---

*[vaadin-dropdown-menu.html, line 161 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19#-Kxpi-u1kdLjq27Ah_3h:-KxqzIppy5luZNabvlNG:boqktqm) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9bcab2e23ee3f54f0f036ad7b231c46f5f05ee2c/vaadin-dropdown-menu.html#L161)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Where is the import, where is the bower.json addition?????
</blockquote></details>

It was working because a transitive dependency in text-field. 
Done

---

*[vaadin-dropdown-menu.html, line 281 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19#-KxplYQFK0lwsZ3-Sjcr:-Kxqzpstp182cs4eiFjQ:b-joxohc) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9bcab2e23ee3f54f0f036ad7b231c46f5f05ee2c/vaadin-dropdown-menu.html#L281)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Changing `this._inputElement` as a side effect in `focusElement`'s getter? Wat?

`_inputElement` isn't even used anymore! It was used in an observer that was removed in this PR. The observer is still listed in the `observers` array however!??? It doesn't warn because a new `_disabledChanged` is inherited from ControlStateMixin (it has different argument list though).
</blockquote></details>

_inputElement is needed to memoize the inputElement and not execute querySelector each time.

Removed the observer.

---

*[test/dropdown-menu-test.html, line 272 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19#-KxpoiGxH_Nf-vkcNu4k:-Kxr-T5jLsau8pmsF44M:b-h9shqp) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/a4880b44ca84f9db8ebb815ea73083e315fc53ac/test/dropdown-menu-test.html#L272)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why were these tests changed (instead of adding new ones)? Should there be a test for the issue this PR aims to fix (tabbing)?
</blockquote></details>

I'm not adding any test in this PR, since the behavior is already tested in the mixin.
I just needed to fix these flaky tests that do not work when body is not focused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19)*

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown-menu.html, line 161 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19#-Kxpi-u1kdLjq27Ah_3h:-KxrBPfyjAPJFF3KOYC7:bs8hoha) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9bcab2e23ee3f54f0f036ad7b231c46f5f05ee2c/vaadin-dropdown-menu.html#L161)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It was working because a transitive dependency in text-field. 
Done
</blockquote></details>

Not done (bower.json)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown-menu.html, line 161 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19#-Kxpi-u1kdLjq27Ah_3h:-KxrPGawBsysZ6oIn6xo:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9bcab2e23ee3f54f0f036ad7b231c46f5f05ee2c/vaadin-dropdown-menu.html#L161)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Not done (bower.json)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/19#-:-KxrQJ9YBReCuAl3NHRH:bnfp4nl)*

**Pull request merged**
