### PR TITLE
Create ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by tomalec**
With live jsbin sample to easily provide code samples for issues.

This is just a proposition. I really like it on Polymer elements, and use it on my repose, such jsbin sample makes it easier to fiddle, try things out, isolate and report problems, check for reproductions.

You may consider cloning this jsbin to your own organization, to keep the ownership.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/126)

### CODE REVIEW

**Comment by limonte** [comment]
@jouni could you take a look at the jsbin from this PR https://jsbin.com/sigesom/edit?html,output

`vaadin-dropdown-menu` looks broken without appropriate parent element.

**Comment by jouni** [comment]
@limonte caused by this line: https://github.com/vaadin/vaadin-text-field/blob/master/src/vaadin-text-field-mixin.html#L79

**Comment by jouni** [comment]
The jsbin is missing the imports for vaadin-list-box and vaadin-item, btw.

**Comment by tomalec** [comment]
> The jsbin is missing the imports...

I updated it to load all `vaadin-*` elements from polygit.

> Should use webcomponents-loader.js btw (vs -lite.js).

Does it mean `vaadin-elements` does not work wit `-lite`?

**Comment by jouni** [comment]
> I updated it to load all vaadin-* elements from polygit.

Thanks 👍 

> Does it mean vaadin-elements does not work wit -lite?

Sure they work. But you should rather use the loader instead, which only loads the polyfills the browser needs (possibly none), not all of them.

Also, the lite bundle has been renamed to [webcomponents-bundle.js](https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-bundle.js) in a newer webcomponentsjs version.

**Comment by tomalec** [comment]
Thanks for the explanation.

> Should use `webcomponents-loader.js` btw (vs `-lite.js`).

done.

**Comment by YuriyVaadin** [comment]
`polygit` has been achieved and is not working in the `jsbin` sample. We need to think about other approach.

**Comment by tomalec** [comment]
Changed to glitch

**Comment by tomalec** [comment]
done

**Comment by web-padawan** [comment]
@tomalec thanks, asked you to join in glitch (so that we could become its owners).

**Comment by web-padawan** [comment]
@tomalec thanks! Sorry, had to update your comment to remove the link as it is not intended for public usage.

**Pull request merged**
