### PR TITLE
Adding Visual tests

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/27)

### CODE REVIEW

**Comment by platosha** [comment]
Why is the IE screenshot so different from the others? See the opened menu.

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[test/visual/dropdown-menu.html, line 26 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky09sVHHkdFP45u0Ym4:-Ky09sVHHkdFP45u0Ym5:b9mmx9l) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L26)):*
> ```HTML
> 
>   <div class="capture-block" id="dropdown-menu">
>     <vaadin-dropdown-menu label="Open" placeholder="Placeholder" id="drop1">
> ```

The opened menu happens to also be the first displayed element on the screenshot page. Thus, it is hardly possible to find out if the menu overlay is positioned over the dropdown or just in the corner of the page. Could you please swap the opened menu with one of the rest to make sure the dropdown opens over a correct place?

---

*[test/visual/dropdown-menu.html, line 53 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky09gBIGE6gH6qZZupW:-Ky09gBIGE6gH6qZZupX:b1k10bz) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L53)):*
> ```HTML
>     <br/>
> 
>     <vaadin-dropdown-menu label="Space">
> ```

This one is almost covered with the menu from above. I wonder if it’s useful this way.

---

*[test/visual/dropdown-menu.html, line 96 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky09FAshGEa8_F2n2LU:-Ky09FAshGEa8_F2n2LV:bjgfvaj) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L96)):*
> ```HTML
> 
>         // This opens and selects an item. Then it removes focus (needed in FF)
>         ['drop3', 'drop4', 'drop5'].forEach(id => select(id, drop => drop.focusElement.blur()));
> ```

Should this be done by setting `value` on the dropdown instead?

---

*[test/visual/dropdown-menu.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky094RFDfWZNFNbgp8f:-Ky094RFDfWZNFNbgp8g:b-8dqigb) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L99)):*
> ```HTML
> 
>         // Using a timeout to so the the last dropdown selected keeps the focus in the screenshot
>         setTimeout(() => select('drop2', drop => window.webComponentsAreReady = true), 100);
> ```

Depending on magic timeout duration number here?

Overall, the amount async and callbacks usage in this piece makes it really confusing to understand.

---

*[test/visual/test.js, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky0AfPeEjAYdG-ganZ9:-Ky0AfPeEjAYdG-ganZA:b-wjo3cm) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/test.js#L12)):*
> ```JavaScript
>             return window.webComponentsAreReady;
>           }, 120000)
>           .wait(10000);
> ```

This makes *additional* wait timeout *after* the page have already reported “webComponentsAreReady”, should not be necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-:-Ky07CqvOGz6MFP9U3AN:b-qa3zdc)*

**Comment by manolo** [comment]
It's a focus issue, the menu is focused when it's opened, IE11 seems not blur when the other input is focused.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[test/visual/dropdown-menu.html, line 53 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky09gBIGE6gH6qZZupW:-Ky0YhnfqGXWgh-7J9SO:bwo0jja) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L53)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This one is almost covered with the menu from above. I wonder if it’s useful this way.
</blockquote></details>

It's intentional, just to have an empty area under the overlay,  I could use an empty div or some CSS but this was easy enough

---

*[test/visual/dropdown-menu.html, line 96 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky09FAshGEa8_F2n2LU:-Ky0YwUDh7KeJg3jd_ly:b7pccih) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L96)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Should this be done by setting `value` on the dropdown instead?
</blockquote></details>

Value was not implemented at this point. Will update when the new branch is merged

---

*[test/visual/dropdown-menu.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky094RFDfWZNFNbgp8f:-Ky0Z3DjRFvtnGRfSe24:b-h7f91d) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L99)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Depending on magic timeout duration number here?

Overall, the amount async and callbacks usage in this piece makes it really confusing to understand.
</blockquote></details>

100 is just enough to open that after the others so as this focus remains

Problem with callbacks here was the lazy creation of the menu. Now in the branch implementing value setting should be easier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-:-Ky0YMWBPD2ShhdbCLbg:brwcqua)*

**Comment by platosha** [comment]
Sounds like something we should fix.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/visual/dropdown-menu.html, line 96 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky09FAshGEa8_F2n2LU:-Ky0cRU0jmPrI5GVBvEB:b32w0x) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L96)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Value was not implemented at this point. Will update when the new branch is merged
</blockquote></details>

OK

---

*[test/visual/dropdown-menu.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky094RFDfWZNFNbgp8f:-Ky0cbdTwHFvYcnPdiOo:b-xp6itk) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L99)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

100 is just enough to open that after the others so as this focus remains

Problem with callbacks here was the lazy creation of the menu. Now in the branch implementing value setting should be easier.
</blockquote></details>

OK got it

Then the value PR would have to remove these workarounds, right? Doesn’t make sense to indroduce them in the first place, I think.

Not gonna block on that though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-:-Ky0aAjOq2DBYYjklMCZ:b-92u0fo)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/visual/test.js, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky0AfPeEjAYdG-ganZ9:-Ky0u2OhBujevp8K-POH:b-cmvs2l) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/test.js#L12)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This makes *additional* wait timeout *after* the page have already reported “webComponentsAreReady”, should not be necessary.
</blockquote></details>

I'll update this PR after that is merged

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27)*

**Comment by manolo** [comment]
@platosha I tried to remove that focused item in IE11 by setting ' item.0.focused = false'  but does not work in Sauce so leaving the code simple without trying to hack that. Anyways that is not a problem of the dropdown itself. 

---

Review status: 11 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/visual/dropdown-menu.html, line 26 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky09sVHHkdFP45u0Ym4:-KyFhlz0GqvMaqJPYWg4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L26)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

The opened menu happens to also be the first displayed element on the screenshot page. Thus, it is hardly possible to find out if the menu overlay is positioned over the dropdown or just in the corner of the page. Could you please swap the opened menu with one of the rest to make sure the dropdown opens over a correct place?
</blockquote></details>

Done.

---

*[test/visual/dropdown-menu.html, line 96 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky09FAshGEa8_F2n2LU:-KyFhn3b8nK8P2mVTfPz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L96)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---

*[test/visual/dropdown-menu.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky094RFDfWZNFNbgp8f:-KyFhqSeUYHAw_8H9b3u:b-uwae64) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/dropdown-menu.html#L99)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK got it

Then the value PR would have to remove these workarounds, right? Doesn’t make sense to indroduce them in the first place, I think.

Not gonna block on that though.
</blockquote></details>

Removed timeout 

---

*[test/visual/test.js, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-Ky0AfPeEjAYdG-ganZ9:-KyFi3SKNq5OkZnKvfkw:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/b0bbb82d738d8907f308ed9f45524bf946f856d7/test/visual/test.js#L12)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I'll update this PR after that is merged
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-:-KyFd-we04sy1ey7nXfF:b-6se64)*

**Comment by platosha** [comment]
@manolo fine. Hope that does not hurt us in future.

---

Reviewed 1 of 11 files at r2.
Review status: 12 of 22 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-:-KyFprP0RLNNNOZMeSTc:b-51o9y1)*

**Comment by platosha** [comment]
:thumbsup: good job!
:lgtm: 

---

Reviewed 1 of 11 files at r2, 5 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-:-KyLkPZ_HUqZ2NbFbLXL:b-8q0jb6)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 11 of 17 files at r1, 1 of 11 files at r2, 5 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/27#-:-KyLobkrOEMP-6p_LGLw:bnfp4nl)*

**Pull request merged**
