### PR TITLE
Adding theme/material

### PR DESCRIPTION
**Pull request by manolo**
Connected to vaadin/vaadin-material-styles#49

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/127)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[bower.json, line 44 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/127#-LEOtFBt9sEOrTOBiI-r:-LEOtFBt9sEOrTOBiI-s:b3aw47i) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/c70721eae7a015a58d347904a17a93859ae89b39/bower.json#L44)):*
> ```JSON
>     "web-component-tester": "^6.1.5",
>     "vaadin-demo-helpers": "^1.2.0",
>     "vaadin-list-box": "^1.0.0",
> ```

Should this be 1.1?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/127)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 44 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/127#-LEOtFBt9sEOrTOBiI-r:-LEOtXcuAyA-Toku6b2-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/c70721eae7a015a58d347904a17a93859ae89b39/bower.json#L44)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should this be 1.1?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/127)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/127#-:-LEOwZ4Y3eiS3iAi3jvd:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/127)*

**Pull request merged**
