### PR TITLE
Do not change value if element is detached.

### LINKED ISSUE #130: Sets value to empty when deleted
### Description
The element sets the bound value to empty when it's deleted. Which is extremely undesired, when the dropdown is used to set a value, then dismissed as a modal or page navigated away in SPA.

Not to mention cases when the data is bound to a proxy, that instantly reacts to the changes with triggering actions on the server.
 
#### Live Demo
https://jsbin.com/zigijed/edit?html,output
 
#### Steps to Reproduce
1. Create and append `vaadin-dropdown-menu` bound to a value
2. Pick a value,
3. Remove `vaadin-dropdown-menu`

```html
<dom-bind id="db">
  <template>
    Please pick a value from `vaadin-dropdown-menu`, then click on the button, observing how the value changes.
    <p>Picked value: <span>{{model.selectedItem}}</span></p>
    <vaadin-dropdown-menu id="dd" label="Label" placeholder="Placeholder" value="{{model.selectedItem}}" on-value-changed="{{remove}}">
      <template>
        <vaadin-list-box>
          <template is="dom-repeat" items="{{model.items}}">
            <vaadin-item value="{{item}}">{{item}}</vaadin-item>
          </template>
          <hr>
          <vaadin-item disabled>Option four</vaadin-item>
        </vaadin-list-box>
      </template>
    </vaadin-dropdown-menu>
    <button id="closeBtn">Click to close once done with selection</button>
  </template>
</dom-bind>
<script>
  db.set('model', {items: ["one", "two"], selectedItem: "one"})
  closeBtn.addEventListener('click', ()=>{
    dd && dd.remove();
  });
</script>
```
 
#### Expected Results
The value should remain as it was picked.
 
#### Actual Results
Value is always set to empty string`""`.
 
### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari 9
- [?] Safari 8
- [x] IE 11
 
### Versions
- vaadin-dropdown-menu: https://github.com/vaadin/vaadin-dropdown-menu/tree/62eca8957aea266514b180564d87e7285874bf84 (master)
- webcomponents: https://github.com/webcomponents/webcomponentsjs/tree/a957286fa3cb157695cb82a1cdd9c822290f73d6(v1)

### PR DESCRIPTION
**Pull request by manolo**
Fixes #130

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @manolo)

---

*[src/vaadin-dropdown-menu.html, line 445 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135#-LFuwNMICoww-tulcGJ-:-LFvEvug2ZzM7ccnC51K:b-n7ah64) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9a050eeef4f77eec1a823451816d5547d796063a/src/vaadin-dropdown-menu.html#L445)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Did you consider the implications to a dropdown menu that's inside a shadow root?
</blockquote></details>

Seems that `contains` also considers shadow content, added tests checking that

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135)*

**Comment by tomivirkki** [comment]
*[src/vaadin-dropdown-menu.html, line 445 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135#-LFuwNMICoww-tulcGJ-:-LFvHnkdE3yaFQzkoqve:b-yd1bl3) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9a050eeef4f77eec1a823451816d5547d796063a/src/vaadin-dropdown-menu.html#L445)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Seems that `contains` also considers shadow content, added tests checking that
</blockquote></details>

I tried setting dropdownmenu.value = 'value' in a demo and it didn't change the selection

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @manolo)

---

*[src/vaadin-dropdown-menu.html, line 445 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135#-LFuwNMICoww-tulcGJ-:-LFvYG662Tbxsn8VKbAX:b-zi8a14) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9a050eeef4f77eec1a823451816d5547d796063a/src/vaadin-dropdown-menu.html#L445)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I tried setting dropdownmenu.value = 'value' in a demo and it didn't change the selection
</blockquote></details>

Yep, contains is not reliable. It's curious that no test failed. Added a failing test and fixed using connected callbacks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135)*

**Comment by tomivirkki** [comment]
*[src/vaadin-dropdown-menu.html, line 445 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135#-LFuwNMICoww-tulcGJ-:-LFvZnOD45BR5mNNhWs7:b54zswh) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9a050eeef4f77eec1a823451816d5547d796063a/src/vaadin-dropdown-menu.html#L445)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Yep, contains is not reliable. It's curious that no test failed. Added a failing test and fixed using connected callbacks.
</blockquote></details>

I don't think it's the right approach to invalidate value handling when detached. The following should still pass, right?

it('should not support settings nonexistent value', function(done) {
  parent.removeChild(dropdown);
  template.items = ['A', 'B', 'C'];

  Polymer.RenderStatus.afterNextRender(dropdown, () => {
    dropdown.value = 'D';
    expect(dropdown.value).not.to.be.equal('D');
    done();
  });
});

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @manolo)

---

*[src/vaadin-dropdown-menu.html, line 445 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135#-LFuwNMICoww-tulcGJ-:-LFxDAMs5i0L_kl335LJ:b72r55i) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/9a050eeef4f77eec1a823451816d5547d796063a/src/vaadin-dropdown-menu.html#L445)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I don't think it's the right approach to invalidate value handling when detached. The following should still pass, right?

it('should not support settings nonexistent value', function(done) {
  parent.removeChild(dropdown);
  template.items = ['A', 'B', 'C'];

  Polymer.RenderStatus.afterNextRender(dropdown, () => {
    dropdown.value = 'D';
    expect(dropdown.value).not.to.be.equal('D');
    done();
  });
});
</blockquote></details>

The point is that `dom-repeat` removes items on detach, hence valid values are removed from the list against a value can be checked, if you set `value = 'B'` when detached it will be set incorrectly to empty `''` when it should remain until it can be actually be checked.

Anyways your test fails also in master because of #14 you need to set the value first to a valid value in order to have a valid test for this case.

I'm adjusting my PR to fix a couple of cases, but I don't see any other easy solution if we want to still keep users value when `dom-repeat` removes temporary the items.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/135)*

**Comment by manolo** [comment]
Closed this PR in favour of https://github.com/vaadin/vaadin-dropdown-menu/pull/137

**Pull request closed without merging**
