### PR TITLE
Listen to items-changed event to update items

### LINKED ISSUE #48: Overlay doesn’t open if list-box is imported after dropdown-menu
https://jsfiddle.net/hf1atr39/

In the fiddle, `vaadin-list-box.html` is imported after `vaadin-dropdown-menu.html`. The user can’t open the dropdown to select an item. No errors in the console.

If you move the list-box import before dropdown-menu, then the element starts working as expected.

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #48 

Listen to items-changed event to update items

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/72)

### CODE REVIEW

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72#-:-KzTot21XbKFpLEXbeUO:bnfp4nl)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-dropdown-menu.html, line 382 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72#-KzTuMa5a5UFSVQtvIzM:-KzTuMa5a5UFSVQtvIzN:balc0vt) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/c641c38f91071d031047d01e3c1a9ec5a9c09425/vaadin-dropdown-menu.html#L382)):*
> ```HTML
>             if (this._menuElement) {
>               this._menuElement.addEventListener('items-changed', e => {
>                 this._items = this._menuElement._navItems;
> ```

IIRC it should rather use `this._menuElement.items`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown-menu.html, line 382 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72#-KzTuMa5a5UFSVQtvIzM:-KzY8PscR8B3hCqxHcMV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/c641c38f91071d031047d01e3c1a9ec5a9c09425/vaadin-dropdown-menu.html#L382)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

IIRC it should rather use `this._menuElement.items`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72#-:-KzY8UZMQ1Pp-VSz-4Hf:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72#-:-KzY94dYiNaqcJmWrYMT:bnfp4nl)*

**Comment by tomivirkki** [comment]
Tests are breaking. [This](https://github.com/vaadin/vaadin-dropdown-menu/commit/d57837f5bed1e121ce7a6b2e9e54464c6b98e197) change would fix them but it might not be the right fix.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72#-:-KzY_Y6h4-ZUZFbjjAwx:b5u9221)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/72)*

**Pull request merged**
