### PR TITLE
Fix data-binding in selected item

### LINKED ISSUE #128: Data-binding does not work in selected item
### Description
Data binding is broken when the option is selected. It updates values on the list, but not in the selection.
 
#### Live Demo
https://jsbin.com/rafumiv/2/edit?html,output
 
#### Steps to Reproduce
1. Create a fragment with
   - `vaadin-dropdown-menu`, with Polymer's binding (`<vaadin-item>{{item}}</vaadin-item>`) inside it,
   - bound an input element to the same value , with Polymer's binding (`<input value="{{item}}">`),
2. Append this fragment to a dom-bind or any Polymer element,
3. Pick the option.
4. Change the value
 
 
#### Expected Results
Value is updated in the dropdown
 
#### Actual Results
There is still the old value.
 
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari 9
- [?] Safari 8
- [x] IE 11
 
### Versions
- vaadin-dropdown-menu: https://github.com/vaadin/vaadin-dropdown-menu/tree/62eca8957aea266514b180564d87e7285874bf84 (master)
- webcomponents: https://github.com/webcomponents/webcomponentsjs/tree/a957286fa3cb157695cb82a1cdd9c822290f73d6(v1)

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #128

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/131)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[src/vaadin-dropdown-menu.html, line 355 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/131#-LFSL5gL47UkRNecbyUx:-LFSL5gL47UkRNecbyUy:blbgi4n) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/07bc53bb634072e54a8238ec1f8afbb1877b6751/src/vaadin-dropdown-menu.html#L355)):*
> ```HTML
>           this.addEventListener('iron-resize', this._boundSetPosition);
> 
>           const origForwardHostProp = this._overlayElement._instance && this._overlayElement._instance.forwardHostProp;
> ```

Why in connectedCallback? _overlayElement is set somewhere else. And its _instance may not be defined.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/131)*

**Comment by web-padawan** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

---

*[src/vaadin-dropdown-menu.html, line 69 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/131#-LFTc8IBDx-037gMVSXE:-LFTc8IBDx-037gMVSXF:b-dkoexu) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/07bc53bb634072e54a8238ec1f8afbb1877b6751/src/vaadin-dropdown-menu.html#L69)):*
> ```HTML
>   <script>
>     (function() {
>       let memorizedTemplate;
> ```

BTW why has this been renamed? "to memoize" is a correct word for this

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/131)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

---

*[src/vaadin-dropdown-menu.html, line 69 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/131#-LFTc8IBDx-037gMVSXE:-LG-P89i6F016tsnvYKE:bqdueg1) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/07bc53bb634072e54a8238ec1f8afbb1877b6751/src/vaadin-dropdown-menu.html#L69)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW why has this been renamed? "to memoize" is a correct word for this
</blockquote></details>

Was thinking it's a typo. Reverted.

---

*[src/vaadin-dropdown-menu.html, line 355 at r1](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/131#-LFSL5gL47UkRNecbyUx:-LG-PBD-67OeYIcwcYXy:b3ywno) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/07bc53bb634072e54a8238ec1f8afbb1877b6751/src/vaadin-dropdown-menu.html#L355)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why in connectedCallback? _overlayElement is set somewhere else. And its _instance may not be defined.
</blockquote></details>

Checking it now in `ready` where the `template` is assigned to the `_overlayElement` and it's defined.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/131)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 6 of 6 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/131#-:-LG01flTBl4E4B1PHJu-:bnfp4nl)*

**Pull request merged**
