### PR TITLE
Should be possible to specify the error message on a dropdown menu.

### LINKED ISSUE #59: It should be possible to specify the error message
Since the dropdown menu can be marked as required, it would be useful in some use cases to specify the error message shown to the end user (e.g. “Please choose one option”).

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #59

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/70)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-dropdown-menu.html, line 260 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70#-KzS_HvSlJHOPSMUa_0A:-KzS_HvSlJHOPSMUa_0B:bbhb1kw) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/a718e32d08ed8c228226b95f3ff1e37b53cf9afe/vaadin-dropdown-menu.html#L260)):*
> ```HTML
> 
>             /**
>              * Error message string for this dropdown - applicable if required is set to True.
> ```

Consider making this description consistent with other elements, e. g.
```
The error message to display when the dropdown menu value is invalid.
```

---

*[demo/dropdown-menu-basic-demos.html, line 75 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70#-KzS_yCFZe-bTiaKzUu4:-KzS_yCFZe-bTiaKzUu5:b-t2snt1) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/a718e32d08ed8c228226b95f3ff1e37b53cf9afe/demo/dropdown-menu-basic-demos.html#L75)):*
> ```HTML
>           <template>
>             <vaadin-list-box>
>               <vaadin-item value="1">Option one</vaadin-item>
> ```

consider adding an option with empty value do user could select it and see the error message.

---

*[test/dropdown-menu-test.html, line 477 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70#-KzS_nVBZIQUa5pKAm_H:-KzS_nVBZIQUa5pKAm_I:b-pu01n) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/a718e32d08ed8c228226b95f3ff1e37b53cf9afe/test/dropdown-menu-test.html#L477)):*
> ```HTML
>           dropdown.validate();
> 
>           const textField = dropdown.shadowRoot.querySelector('vaadin-dropdown-menu-text-field');
> ```

the reference to this element is already stored in the `input` variable so better use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70)*

**Comment by vicsstar** [comment]
*[vaadin-dropdown-menu.html, line 260 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70#-KzS_HvSlJHOPSMUa_0A:-KzTLJdGITkDn57d1JMv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/a718e32d08ed8c228226b95f3ff1e37b53cf9afe/vaadin-dropdown-menu.html#L260)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Consider making this description consistent with other elements, e. g.
```
The error message to display when the dropdown menu value is invalid.
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70)*

**Comment by vicsstar** [comment]
*[demo/dropdown-menu-basic-demos.html, line 75 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70#-KzS_yCFZe-bTiaKzUu4:-KzTLMa1_F4xyJxS5ad4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/a718e32d08ed8c228226b95f3ff1e37b53cf9afe/demo/dropdown-menu-basic-demos.html#L75)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

consider adding an option with empty value do user could select it and see the error message.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70)*

**Comment by vicsstar** [comment]
*[test/dropdown-menu-test.html, line 477 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70#-KzS_nVBZIQUa5pKAm_H:-KzTLQwc8LbbbLcDfdXn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/a718e32d08ed8c228226b95f3ff1e37b53cf9afe/test/dropdown-menu-test.html#L477)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

the reference to this element is already stored in the `input` variable so better use it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70#-:-KzT_gT-657pD33Db_iC:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/70#-:-KzTbC6jxjpnjqGi1orX:bnfp4nl)*

**Pull request merged**
