### PR TITLE
Replace external images with public domain ones. Fixes #20

### LINKED ISSUE #20: Clean up demos
Remove:
screenshot 2017-11-01 06 41 13

Don't use `http://www.sciencekids.co.nz` resources in the demos (the flags). Use emoji for example.

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/25)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/dropdown-menu-basic-demos.html, line 78 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/25#-KxrYII8qfRpJviBQb-j:-KxrYII8qfRpJviBQb-k:b-24forz) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/2afbc850d8d70ab26d6aebbac4f62d77129f5385/demo/dropdown-menu-basic-demos.html#L78)):*
> ```HTML
>               <vaadin-list-box>
>                 <vaadin-item>
>                   
> ```

This violates the DRY and SoC principles. Separate styles from the markup and put them to one place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/25)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/dropdown-menu-basic-demos.html, line 78 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/25#-KxrYII8qfRpJviBQb-j:-KxraEhoYMKHkWfrm_OF:baytj61) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/2afbc850d8d70ab26d6aebbac4f62d77129f5385/demo/dropdown-menu-basic-demos.html#L78)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

This violates the DRY and SoC principles. Separate styles from the markup and put them to one place.
</blockquote></details>

Styles do not apply in this case because the node is cloned and moved to a different scope

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/25)*

**Comment by limonte** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/dropdown-menu-basic-demos.html, line 78 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/25#-KxrYII8qfRpJviBQb-j:-Kxrd4mYoMb5hpFbsl8W:b-8ndtzf) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/2afbc850d8d70ab26d6aebbac4f62d77129f5385/demo/dropdown-menu-basic-demos.html#L78)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Styles do not apply in this case because the node is cloned and moved to a different scope
</blockquote></details>

Ok, not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/25)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/25#-:-KxreNxeAXGsBDTL9A0i:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/25#-:-KxrfPHz2dME-M7uuvvL:bnfp4nl)*

**Pull request merged**
