### PR TITLE
Set padding in vertical mode

### LINKED ISSUE #30: Menu is cropped from the bottom inn Mobile Safari in landscape orientation when navbar is visible
screen shot 2017-11-08 at 8 57 44

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #30

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/71)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-dropdown-menu.html, line 471 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/71#-KzSktCcVYxfQ7iWb9UQ:-KzSktCcVYxfQ7iWb9UR:b-6iwa5j) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/efc8b132fe15d4ca7010cfa69afcb212f07f8a6c/vaadin-dropdown-menu.html#L471)):*
> ```HTML
>           const innerWidth = window.innerWidth;
> 
>           const vertical = (innerWidth > innerHeight) ? true : false;
> ```

Consider using more explicit detection, maybe `matchMedia` would help?
```
window.matchMedia("(orientation: portrait)").matches
```

Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/71)*

**Comment by manolo** [comment]
please rebase, and wait for the other PR to be released and released. Then :lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/71#-:-KzTO1DNB8mqNiEi_ggq:b1y07wl)*

**Comment by web-padawan** [comment]
please bump `polymer analyse vaadin-dropdown-menu.html > analysis.json` and ensure the analysis doesn't contain demo-related stuff like it does on master. other than that :lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[vaadin-dropdown-menu.html, line 471 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/71#-KzSktCcVYxfQ7iWb9UQ:-KzbyL9ArD_GgVdwGVao:b-btydwa) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/efc8b132fe15d4ca7010cfa69afcb212f07f8a6c/vaadin-dropdown-menu.html#L471)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Consider using more explicit detection, maybe `matchMedia` would help?
```
window.matchMedia("(orientation: portrait)").matches
```

Not a blocker.
</blockquote></details>

Corresponding code moved to overlay, resolving this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/71#-:-KzbxrGhHBQjtqjlLNQt:b-vxrmi3)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/71)*

**Pull request merged**
