### PR TITLE
Add animation tests

### PR DESCRIPTION
**Pull request by limonte**
Connected to https://github.com/vaadin/vaadin-overlay/issues/80

The test suite to prove https://github.com/vaadin/vaadin-overlay/issues/80

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116#-LATUxGb0DW_MB320OI2:-LAXdUUt0sPr3xJ41APF:b8npixi) (no related file):*
> If that’s an issue in <vaadin-overlay>, should be tested in that repo I believe.

For some reason, even for overlay with animations, I'm not able to write a test case on the `vaadin-overlay` side which is failing and therefore proving the issue.

---

*[test/animations-test.html, line 38 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116#-LATUIyeC-7WwlS2-FJT:-LAXd2Ig-O7Ss0ha60yW:b5etpcs) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/ecbad64f476161dd4c2f110a0a4ec46e47bf10bf/test/animations-test.html#L38)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Not sure what you’re clicking here, but bear in mind that `document.activeElement` is not polyfilled in Safari 9. ShadyDOM defines `document._activeElement` there, so you would have to use both:
`document._activeElement || document.activeElement`.

Or find the stable reference to some element and click that (`document.documentElement` or `document.body` maybe?).
</blockquote></details>

Oh, thanks for mentioning the detail about `document.activeElement` for Safari 9, didn't know that. Moved to the `getActiveMenuItem()` helper method to be more understandable.

---

*[test/animations-test.html, line 42 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116#-LATRNCS90Ju6L_2EYv2:-LAXdLv95iVMIEr15z2p:b1i6idd) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/ecbad64f476161dd4c2f110a0a4ec46e47bf10bf/test/animations-test.html#L42)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Well, you can do something like this:

```javascript
function afterAnimation(el, callback) {
  const name = getComputedStyle(el).getPropertyValue('animation-name');
  if (name && name != 'none') {
    const listener = () => {
      this.removeEventListener('animationend', listener);
      callback();
    };
    this.addEventListener('animationend', listener);
  } else {
    callback();
  }
}

afterAnimation(dropdown._overlayElement, () => {
  expect(...);
  done();
});
```

Or this:

```javascript
function afterRemovalFromBody(overlay, callback) {
  if (overlay.parentNode !== document.body) {
    callback();
    return;
  }

  new MutationObserver((records, observer) => {
    records.forEach(record => {
      if (Array.from(record.removedNodes).indexOf(overlay) !== -1) {
        observer.disconnect();
        callback();
      }
    });
  }).observe(document.body, {childList: true});
}

afterRemovalFromBody(dropdown._overlayElement, () => {
  ...
});
```
</blockquote></details>

Done by using the lovely `afterAnimation` helper method, thanks a lot!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[test/animations-test.html, line 29 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116#-LAYIhte2a68fNbe6Bk-:-LAYIhte2a68fNbe6Bk0:b-3npmon) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/e239b1d1ca9fefcc0a7b5314cba2e8b74e32f563/test/animations-test.html#L29)):*
> ```HTML
>   <script>
>     function getActiveMenuItem() {
>       return document._activeElement || document.activeElement;
> ```

BTW This relies on that the overlay stamps children in global scope. While true for that case, in general it’s an implementation detail of the overlay.

The overlay has API for the content, would be nicer to use that: `dropdown._overlayElement.content.querySelector('mock-item')`

Not a blocker though.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116#-:-LAYJRnO4BH1FTBqIKPI:bnfp4nl)*

**Comment by limonte** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/animations-test.html, line 29 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116#-LAYIhte2a68fNbe6Bk-:-LAYL-vi6wQ64kC5LfCB:bcwmfel) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/e239b1d1ca9fefcc0a7b5314cba2e8b74e32f563/test/animations-test.html#L29)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW This relies on that the overlay stamps children in global scope. While true for that case, in general it’s an implementation detail of the overlay.

The overlay has API for the content, would be nicer to use that: `dropdown._overlayElement.content.querySelector('mock-item')`

Not a blocker though.
</blockquote></details>

Valid point, done :+1:

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116)*

**Comment by limonte** [comment]
I re-ran tests, they are passing now.

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/116#-:-LBVTRQp4fwU8y2j7oQ-:bnfp4nl)*

**Pull request merged**
