### PR TITLE
Select the appropriate item when value is set

### LINKED ISSUE #15: When setting the value, item in the overlay should be selected
It needs some changes in `vaadin-list-box` see  https://github.com/vaadin/vaadin-list-box/issues/7

### PR DESCRIPTION
**Pull request by manolo**
Fixes #15

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/28)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-:-Ky0pYAKUKogY4cYTmFt:bnfp4nl)*

**Comment by tomivirkki** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 394 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-Ky11MIsqGBKjp1t3X32:-Ky11MIsqGBKjp1t3X33:b9369vk) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/58e7b6be6042c182ab3379bfbb3d9400b88c403c/vaadin-dropdown-menu.html#L394)):*
> ```HTML
>           if (this._menuElement && this._menuElement._navItems) {
>             this._menuElement.selected = this._menuElement._navItems.reduce((prev, item, idx) => {
>               return item.getAttribute('value') == value ? idx : prev;
> ```

Should check for the property, not attribute

---

*[test/dropdown-menu-test.html, line 129 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-Ky11Rw-fAJtBhTx58pr:-Ky11Rw-fAJtBhTx58ps:b-wyjv7g) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/58e7b6be6042c182ab3379bfbb3d9400b88c403c/test/dropdown-menu-test.html#L129)):*
> ```HTML
>         });
> 
>         it('Should not update value if the selected item has not a `value` attribute', () => {
> ```

Why? Property should be enough not that `<vaadin-item>` has the property.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by manolo** [comment]
Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 394 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-Ky11MIsqGBKjp1t3X32:-KyFGeV3NUxcGdHWA_8Y:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/58e7b6be6042c182ab3379bfbb3d9400b88c403c/vaadin-dropdown-menu.html#L394)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should check for the property, not attribute
</blockquote></details>

Done.

---

*[test/dropdown-menu-test.html, line 129 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-Ky11Rw-fAJtBhTx58pr:-KyFTL-Og6Hb8VBBVnoQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/58e7b6be6042c182ab3379bfbb3d9400b88c403c/test/dropdown-menu-test.html#L129)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why? Property should be enough not that `<vaadin-item>` has the property.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by tomivirkki** [comment]
*[vaadin-dropdown-menu.html, line 413 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFuNw5wc2e19mCqq2q:-KyFuNw5wc2e19mCqq2r:b-9l4jax) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L413)):*
> ```HTML
>             this._menuElement.selected = this._menuElement._navItems.reduce((prev, item, idx) => {
>               return item.value == this.value ? idx : prev;
>             }, -1);
> ```

Why `-1`? That's not the default for a list-box with no selection

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by tomivirkki** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 220 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFuzbZTlC-b-5l7svi:-KyFuzbZTlC-b-5l7svj:b-rtnd6) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L220)):*
> ```HTML
>               value: '',
>               notify: true,
>               observer: '_updateSelectedMenu'
> ```

To align with most of our elements, this should call `_valueChanged` which in turn calls `_updateSelectedMenu`. I agree with @limonte that calling observer functions directly is bad practice.

---

*[vaadin-dropdown-menu.html, line 259 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFvQLaHdrH_Y6VNlPz:-KyFvQLaHdrH_Y6VNlQ-:bburio0) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L259)):*
> ```HTML
>             _nativeInput: Object,
> 
>             // Used for setting a value to the input in order to show/hidde placeholder
> ```

hidde? I also spotted that in the commit message

---

*[vaadin-dropdown-menu.html, line 396 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFvn8NQ_p3QBgJuYUg:-KyFvn8NQ_p3QBgJuYUh:b-edtrc1) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L396)):*
> ```HTML
>               clone.removeAttribute('tabindex');
>               this._selectionElement.appendChild(clone);
>               this._valueForInput = selected.children.length || selected.textContent.trim() || '';
> ```

What is this??? Why should the internal `<input>` have a number of the selected item children as value? And the line above sets the value either to "true" or "false"!!?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by manolo** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 413 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFuNw5wc2e19mCqq2q:-KyFyHikrc2QBzr7v120:btwoovt) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L413)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why `-1`? That's not the default for a list-box with no selection
</blockquote></details>

Any index out of the range  `0 - items.length` works here because list-box would select the item in that position if found. `-1` is quite used in javascript as a non existing index, and it's shorter than `undefined` or `null`, not that  `0` or `empty` cannot be used here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by tomivirkki** [comment]
*[vaadin-dropdown-menu.html, line 413 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFuNw5wc2e19mCqq2q:-KyG13YWBIVmq6hMDPD-:b-uvh6th) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L413)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Any index out of the range  `0 - items.length` works here because list-box would select the item in that position if found. `-1` is quite used in javascript as a non existing index, and it's shorter than `undefined` or `null`, not that  `0` or `empty` cannot be used here
</blockquote></details>

It's not `-1` by default when no item is selected so don't use `-1`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by manolo** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 220 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFuzbZTlC-b-5l7svi:-KyG-2O9GuyuQlvh--d8:b-1lzqzc) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L220)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

To align with most of our elements, this should call `_valueChanged` which in turn calls `_updateSelectedMenu`. I agree with @limonte that calling observer functions directly is bad practice.
</blockquote></details>

I disagree. Having a dumb empty function here looks useless. But changed anyways.

---

*[vaadin-dropdown-menu.html, line 396 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFvn8NQ_p3QBgJuYUg:-KyG03SLTE5X49qEOLVo:b-5igaai) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L396)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

What is this??? Why should the internal `<input>` have a number of the selected item children as value? And the line above sets the value either to "true" or "false"!!?
</blockquote></details>

Ups, good catch in the line above, the double `!!` was left by accident, and even worst, the test checking that was wrong. Fixed.
 
`true` or `false` sets the `has-value` true, so we need here empty or undefined strings, for the case of label, I set the text content as well as when the `vaadin-item` has text, but when there are items, we need something, a number is ok for togging the `has-value` textContent of children, might not work for instance when having an img.

---

*[vaadin-dropdown-menu.html, line 413 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFuNw5wc2e19mCqq2q:-KyG2-zWqyh9s9i34dbh:b-uxmqvr) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L413)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

It's not `-1` by default when no item is selected so don't use `-1`
</blockquote></details>

Yes, I know that is undefined. I explained that -1 is shorter than undefined and does not affects the logic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by manolo** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 259 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFvQLaHdrH_Y6VNlPz:-KyG2yUywmwGMc5XYUqr:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L259)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

hidde? I also spotted that in the commit message
</blockquote></details>

Done.

---

*[vaadin-dropdown-menu.html, line 413 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFuNw5wc2e19mCqq2q:-KyG3-Fxp9dsLgS05ngo:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L413)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Yes, I know that is undefined. I explained that -1 is shorter than undefined and does not affects the logic.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by tomivirkki** [comment]
*[vaadin-dropdown-menu.html, line 260 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyG6ClsxuAc5b-BTyXS:-KyG6ClsxuAc5b-BTyXT:byzscua) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/24abfe61093f74cd193810dcd78ad1d5bfe0f3e7/vaadin-dropdown-menu.html#L260)):*
> ```HTML
> 
>             // Used for setting a value to the input in order to show/hide placeholder
>             _valueForInput: Object
> ```

This is bad misuse of `has-value`. You really should use other means for hiding the input. A dedicated attribute or something. But the current approach requires you to place some text inside input if when you want to hide it which sounds wrong to begin with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by tomivirkki** [comment]
*[vaadin-dropdown-menu.html, line 396 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFvn8NQ_p3QBgJuYUg:-KyG5aixxkXBeVrpYOcQ:b-slb8zw) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L396)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Ups, good catch in the line above, the double `!!` was left by accident, and even worst, the test checking that was wrong. Fixed.
 
`true` or `false` sets the `has-value` true, so we need here empty or undefined strings, for the case of label, I set the text content as well as when the `vaadin-item` has text, but when there are items, we need something, a number is ok for togging the `has-value` textContent of children, might not work for instance when having an img.
</blockquote></details>

Use a dedicated attribute or something. `has-value` is not the right way to hide the input.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by manolo** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 396 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFvn8NQ_p3QBgJuYUg:-KyGpNcx_By_aSjiYh0Y:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L396)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Use a dedicated attribute or something. `has-value` is not the right way to hide the input.
</blockquote></details>

Done.

---

*[vaadin-dropdown-menu.html, line 260 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyG6ClsxuAc5b-BTyXS:-KyGpLy49HLe5n7_Stp1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/24abfe61093f74cd193810dcd78ad1d5bfe0f3e7/vaadin-dropdown-menu.html#L260)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This is bad misuse of `has-value`. You really should use other means for hiding the input. A dedicated attribute or something. But the current approach requires you to place some text inside input if when you want to hide it which sounds wrong to begin with.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by YuriyVaadin** [comment]
Seems to be working correctly :lgtm: 

---

Reviewed 1 of 3 files at r2, 1 of 3 files at r3, 3 of 3 files at r4, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[demo/dropdown-menu-basic-demos.html, line 77 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyKO_6at8QgFKRbUabi:-KyKO_6at8QgFKRbUabj:b-rcle8l) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/demo/dropdown-menu-basic-demos.html#L77)):*
> ```HTML
>                 <vaadin-item value="" label="">Other</vaadin-item>
>                 <vaadin-item value="ES" label="Spanish">Spanish (default)</vaadin-item>
>                 <vaadin-item value="FI" label="Finish">Finish</vaadin-item>
> ```

Nit: `Finnish`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-:-KyKPn8eH7D9JMFuPeWW:b1b5lbs)*

**Comment by manolo** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 220 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFuzbZTlC-b-5l7svi:-KyGp8Y8uFX7YtgoduKX:boktd20) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L220)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I disagree. Having a dumb empty function here looks useless. But changed anyways.
</blockquote></details>

Changed code to trigger the function by setting the items property in the callback, instead of calling the function.

---

*[demo/dropdown-menu-basic-demos.html, line 77 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyKO_6at8QgFKRbUabi:-KyLFykCcTa6PIp7aiLS:b-vz3yex) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/demo/dropdown-menu-basic-demos.html#L77)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Nit: `Finnish`
</blockquote></details>

Ups. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-:-KyLUWud7PRsmPAvS8TR:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[vaadin-dropdown-menu.html, line 220 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28#-KyFuzbZTlC-b-5l7svi:-KyLfxUl1ZcRLwQ_D7ZV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1cb98998d438fee4552938b6ecf8ce9276f9ae6d/vaadin-dropdown-menu.html#L220)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Changed code to trigger the function by setting the items property in the callback, instead of calling the function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Comment by manolo** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/28)*

**Pull request merged**
