### PR TITLE
Cleanup tests, avoid dependency on <vaadin-item>

### PR DESCRIPTION
**Pull request by platosha**
Connected to #57

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/69)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown-menu.html, line 513 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/69#-KzOxzHvbbuHDc9TbmHg:-KzOxzHvbbuHDc9TbmHh:b-vuqirc) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/796c27bb4f7ed4cd66a14a4ac86cfe2afd3f938b/vaadin-dropdown-menu.html#L513)):*
> ```HTML
>         }
> 
>         _setFocused(focused) {
> ```

why is this removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/69)*

**Comment by platosha** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown-menu.html, line 513 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/69#-KzOxzHvbbuHDc9TbmHg:-KzPBxh1HQU3HOQ_6K3B:b2cvgcv) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/796c27bb4f7ed4cd66a14a4ac86cfe2afd3f938b/vaadin-dropdown-menu.html#L513)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why is this removed?
</blockquote></details>

Oops, that was unintentional. Reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/69)*

**Comment by web-padawan** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/dropdown-menu-test.html, line 325 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/69#-KzSU8ipkdp5exMaSEfH:-KzSU8ipkdp5exMaSEfI:b-k5pchf) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/796c27bb4f7ed4cd66a14a4ac86cfe2afd3f938b/test/dropdown-menu-test.html#L325)):*
> ```HTML
>         });
> 
>         it('Should set tabindex attribute to -1 on the native input', () => {
> ```

Why is this test removed? It was added to check if the workaround to prevent tabbing into native input is applied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/69)*

**Comment by platosha** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/dropdown-menu-test.html, line 325 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/69#-KzSU8ipkdp5exMaSEfH:-KzSiUZxFmloNdoPOq-D:b-nr8aym) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/796c27bb4f7ed4cd66a14a4ac86cfe2afd3f938b/test/dropdown-menu-test.html#L325)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Why is this test removed? It was added to check if the workaround to prevent tabbing into native input is applied.
</blockquote></details>

Oh, sorry, not intentional removal. Reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/69)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/69)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/69#-:-KzTZS4zdbkxx9aNlQFe:bnfp4nl)*

**Pull request merged**
