### PR TITLE
Fix visual tests

### LINKED ISSUE #85: Visual tests broken
The value is not selected in the "Html as Content" test due to the [change](https://github.com/vaadin/vaadin-item/commit/f624672345bc56afa0919b87413343fea54a45a4) in vaadin-item.

One possible workaround to make it pass is to use value for both dropdown menu and item in the demo, e. g. like in [this row](https://github.com/vaadin/vaadin-dropdown-menu/blob/master/test/visual/dropdown-menu.html#L76).

IMO, It would be better to set `value="Html as Content"` on the dropdown explicitly, but that is currently not possible due to the `&nbsp;` characters.

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #85 

Fix visual tests.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/88)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/test.js, line 7 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/88#-KzxHKDSdJ_xQk8c_zF8:-KzxHKDSdJ_xQk8c_zF9:bsnsw5) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/053c31a3a568b03c38679bf7818868e1e8cd39b7/test/visual/test.js#L7)):*
> ```JavaScript
>       .setUrl('/dropdown-menu.html')
>       .setCaptureElements('#dropdown-menu')
>       .before(actions => {
> ```

Is that a really necessary change?

When I run gemini, I see screenshots in a consistent state, although not matching the screenshots in repo. Does not look like non-upgraded or something totally wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/88)*

**Comment by web-padawan** [comment]
The original regression in the `Item as value` test, which I described in the issue, is not fixed. Might be a separate task though.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/88#-:-KzwzniDDX5AJnKHZSSO:bfhci79)*

**Comment by platosha** [comment]
AFAIK screenshots are broken due to `<vaadin-item>`’s value behavior change.

I would just update the test html file with explicit values. Once this is done, no need for any changes in test setup or among screenshots:

```diff
diff --git a/test/visual/dropdown-menu.html b/test/visual/dropdown-menu.html
index c5a88a1..b6ab07b 100644
--- a/test/visual/dropdown-menu.html
+++ b/test/visual/dropdown-menu.html
@@ -50,7 +50,7 @@
 
     <br/>
 
-    <vaadin-dropdown-menu label="Item as value" placeholder="Placeholder">
+    <vaadin-dropdown-menu label="Item as value" placeholder="Placeholder" value="Html&nbsp;as&nbsp;Content">
       <template>
         <vaadin-list-box>
           <vaadin-item><strong>Html</strong>&nbsp;as&nbsp;<i>Content</i></vaadin-item>
@@ -58,7 +58,7 @@
       </template>
     </vaadin-dropdown-menu>
 
-    <vaadin-dropdown-menu label="Open" placeholder="Placeholder" id="drop1">
+    <vaadin-dropdown-menu label="Open" placeholder="Placeholder" id="drop1" value="Item one">
       <template>
         <vaadin-list-box>
           <strong>Opened menu</strong>
@@ -78,7 +78,7 @@
       </template>
     </vaadin-dropdown-menu>
 
-    <vaadin-dropdown-menu label="Label as Content" placeholder="Placeholder">
+    <vaadin-dropdown-menu label="Label as Content" placeholder="Placeholder" value="Option one">
       <template>
         <vaadin-list-box>
           <vaadin-item label="Label as Content">Option one</vaadin-item>
```

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/88#-:-KzxIIUmIPw_t9c0Tjbr:b-89gyl4)*

**Comment by platosha** [comment]
(Copy the lines below and run `$ pbpaste | git apply` to apply the patch.)

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/88#-:-KzxLiwqSBjojuPYEBr0:b-b0itb1)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/88#-:-KzxOX5VxD6XLBFGxJXa:bnfp4nl)*

**Pull request merged**
