### PR TITLE
Prevent Firefox from disallowing click on input

### LINKED ISSUE #38: Doesn't open on Firefox by clicking the input
When there's no pre-selected value in the dropdown menu, the overlay doesn't open by clicking the contained `vaadin-text-field`

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #38

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/39)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/39#-KyZWa5eGf38D-dyVgq8:-KyZWa5eGf38D-dyVgq9:b3893en) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/83c6a43faa4fd91fd6b1444e904013ba58be16b8/vaadin-dropdown-menu.html#L52)):*
> ```HTML
>        * 1. Override native styling for disabled-inputs so as placeholder looks ok.
>        * 2. Prevent Firefox from preveting click event on the disabled input.
>        */
> ```

I find the comments here difficult to maintain, and not easy to read. 
At the beginning I wondered what those numbers meant until I read the comment.
I'd rather a single line above each rule

```
   [part="value"]:disabled {
        /* Override native styling for disabled-inputs so as placeholder looks ok. */
        opacity: 1; 
        /* Prevent Firefox from preveting click event on the disabled input. */
        pointer-events: none;
      }
```

---

*[vaadin-dropdown-menu.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/39#-KyZWHxNH_H8C09iE_Pu:-KyZWHxNH_H8C09iE_Pv:btwx62z) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/83c6a43faa4fd91fd6b1444e904013ba58be16b8/vaadin-dropdown-menu.html#L55)):*
> ```HTML
>       [part="value"]:disabled {
>         opacity: 1; /* 1 */
>         pointer-events: none; /* 2 */
> ```

Is this rule needed in the `:disabled` pseudo? probably is better to set to the value  always, to avoid clicking if disabled flag is removed by accident.

Actually I'm thinking that the hack setting the input as disabled in code might be removed, as well as the opacity workaround if pointer events works always.  Could you remove it and see if the issue #23 does not happen just by setting the pointer events? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/39)*

**Comment by web-padawan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/39#-KyZWa5eGf38D-dyVgq8:-KyZoPe1g-vbkTuVC82S:b-e6d4lc) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/83c6a43faa4fd91fd6b1444e904013ba58be16b8/vaadin-dropdown-menu.html#L52)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I find the comments here difficult to maintain, and not easy to read. 
At the beginning I wondered what those numbers meant until I read the comment.
I'd rather a single line above each rule

```
   [part="value"]:disabled {
        /* Override native styling for disabled-inputs so as placeholder looks ok. */
        opacity: 1; 
        /* Prevent Firefox from preveting click event on the disabled input. */
        pointer-events: none;
      }
```
</blockquote></details>

Just to clarify these comments: I was inspired by `normalize.css` but you're right, the simpler is the better.

---

*[vaadin-dropdown-menu.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/39#-KyZWHxNH_H8C09iE_Pu:-KyZoaBwBwLzIhLjZzqO:b-v5ed6o) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/83c6a43faa4fd91fd6b1444e904013ba58be16b8/vaadin-dropdown-menu.html#L55)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Is this rule needed in the `:disabled` pseudo? probably is better to set to the value  always, to avoid clicking if disabled flag is removed by accident.

Actually I'm thinking that the hack setting the input as disabled in code might be removed, as well as the opacity workaround if pointer events works always.  Could you remove it and see if the issue #23 does not happen just by setting the pointer events? 
</blockquote></details>

I tested in iOS simulator and pointer events worked for me. Removed the previous hack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/39)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-dropdown-menu.html, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/39#-KyZWHxNH_H8C09iE_Pu:-Ky_-bv3_qO7p29gsjCB:b-8fx2u7) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/83c6a43faa4fd91fd6b1444e904013ba58be16b8/vaadin-dropdown-menu.html#L55)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

I tested in iOS simulator and pointer events worked for me. Removed the previous hack.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/39#-:-Ky_0CqpRYL_h5BwBuQY:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/39)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/39)*

**Pull request merged**
