### PR TITLE
Prepare for P3 conversion

### LINKED ISSUE #108: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by platosha**
Fixes #108

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 20 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.travis.yml, line 26 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111#-L9KgWJK8R-On9Lp5bhM:-L9KgWJK8R-On9Lp5bhN:b-drk1ir) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1b23f9176f1608107486b529c203e60c95fcf1eb/.travis.yml#L26)):*
> ```YAML
>       npm install -g polymer-cli &&
>       npm install &&
>       gulp lint &&
> ```

BTW also version:check

---

*[.travis.yml, line 27 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111#-L9KgexDBvlnLrmEdyeV:-L9KgexDBvlnLrmEdyeW:bv9w25a) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1b23f9176f1608107486b529c203e60c95fcf1eb/.travis.yml#L27)):*
> ```YAML
>       npm install &&
>       gulp lint &&
>       polymer lint --rules polymer-2 --input *.html &&
> ```

this should be updated to restore paths for src and theme:
```
polymer lint --rules polymer-2 --input ./src/*.html ./theme/**/*.html &&
```

see vaadin/vaadin-element-skeleton@9a4856e

---

*[wct.conf.js, line 8 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111#-L9KgsQ4-ZHaxAf_Yzf5:-L9KgsQ4-ZHaxAf_Yzf6:bkjjeiu) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1b23f9176f1608107486b529c203e60c95fcf1eb/wct.conf.js#L8)):*
> ```JavaScript
>     var saucelabsPlatforms = [
>       'macOS 10.12/iphone@10.3',
>       'macOS 10.12/ipad@11.0',
> ```

Let's also add Chrome and Firefox here, see vaadin/vaadin-element-skeleton@e41d49d

---

*[test/dropdown-menu-test.html, line 377 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111#-L9KhpkY-s43kin7SgP0:-L9Khhs86V9eTX0p9S32:b-hlmsb9) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1b23f9176f1608107486b529c203e60c95fcf1eb/test/dropdown-menu-test.html#L377)):*
> ```HTML
>         it('overlay should be opened on click event on input field', () => {
>           expect(dropdown._overlayElement.opened).to.be.false;
>           input.shadowRoot.querySelector('[part="input-field"]').dispatchEvent(
> ```

BTW can be changed to `input.focusElement` which is the reference to that input-field part

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111)*

**Comment by platosha** [comment]
Review status: 16 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 26 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111#-L9KgWJK8R-On9Lp5bhM:-L9Kn3OI5bCMlQysbAF9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1b23f9176f1608107486b529c203e60c95fcf1eb/.travis.yml#L26)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW also version:check
</blockquote></details>

Done.

---

*[.travis.yml, line 27 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111#-L9KgexDBvlnLrmEdyeV:-L9Kn4LX1cF4xeu_5thG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1b23f9176f1608107486b529c203e60c95fcf1eb/.travis.yml#L27)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

this should be updated to restore paths for src and theme:
```
polymer lint --rules polymer-2 --input ./src/*.html ./theme/**/*.html &&
```

see vaadin/vaadin-element-skeleton@9a4856e
</blockquote></details>

Done.

---

*[wct.conf.js, line 8 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111#-L9KgsQ4-ZHaxAf_Yzf5:-L9Kn54yE5Q7ZPzZ0wE9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1b23f9176f1608107486b529c203e60c95fcf1eb/wct.conf.js#L8)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Let's also add Chrome and Firefox here, see vaadin/vaadin-element-skeleton@e41d49d
</blockquote></details>

Done.

---

*[test/dropdown-menu-test.html, line 377 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111#-L9KhpkY-s43kin7SgP0:-L9Kn5b52kj5R1rEhXgf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/1b23f9176f1608107486b529c203e60c95fcf1eb/test/dropdown-menu-test.html#L377)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW can be changed to `input.focusElement` which is the reference to that input-field part
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111)*

**Comment by web-padawan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-dropdown-menu/111#-:-L9KvFOhEZYdLh3aWc8K:bnfp4nl)*

**Pull request merged**
