### PR TITLE
Initial alternative prototype functionality

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Connected to https://github.com/vaadin/vaadin-core/issues/136

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/4)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 60 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4#-KxITyYSmr_4jC7iUs5C:-KxITyYSmr_4jC7iUs5D:bnngt3b) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/96fc2a426983cd0fb24f711938095eee299f9c4b/vaadin-dropdown-menu.html#L60)):*
> ```HTML
>         * ### Styling
>         *
>         * The following Shadow DOM parts are available for styling:
> ```

Link instead of copying the docs

---

*[vaadin-dropdown-menu.html, line 88 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4#-KxITibQA-skDZ_F67s1:-KxITibQA-skDZ_F67s2:bnngt3b) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/96fc2a426983cd0fb24f711938095eee299f9c4b/vaadin-dropdown-menu.html#L88)):*
> ```HTML
>         * ### Styling
>         *
>         * The following shadow DOM parts are available for styling:
> ```

Link instead of copying the docs

---

*[vaadin-dropdown-menu.html, line 168 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4#-KxITnIlefu8ukat2hyz:-KxITnIlefu8ukat2hz-:bjbs33x) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/96fc2a426983cd0fb24f711938095eee299f9c4b/vaadin-dropdown-menu.html#L168)):*
> ```HTML
>               type: String,
>               value: '',
>               reflectToAttribute: true,
> ```

Shouldn't notify or reflect to attribute

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-dropdown-menu.html, line 60 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4#-KxITyYSmr_4jC7iUs5C:-KxIXqRohtExrunId98h:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/96fc2a426983cd0fb24f711938095eee299f9c4b/vaadin-dropdown-menu.html#L60)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Link instead of copying the docs
</blockquote></details>

Done.

---

*[vaadin-dropdown-menu.html, line 88 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4#-KxITibQA-skDZ_F67s1:-KxIXpxD05viBQMxY2mx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/96fc2a426983cd0fb24f711938095eee299f9c4b/vaadin-dropdown-menu.html#L88)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Link instead of copying the docs
</blockquote></details>

Done.

---

*[vaadin-dropdown-menu.html, line 168 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4#-KxITnIlefu8ukat2hyz:-KxIXrYKiJvVP9shmfw7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/96fc2a426983cd0fb24f711938095eee299f9c4b/vaadin-dropdown-menu.html#L168)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Shouldn't notify or reflect to attribute
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4)*

**Comment by manolo** [comment]
In this approach I see a couple of issues
- We shouldn't use `slot="prefix"`, because we already need it  in all form elements . So in order to align with date-picker, text-field and combo-box, we should forward those slots to the internal text-field.
- The approach does not support content with multiple children like `<vaadin-item><span ...></span></vaadin-item>`. Obviously the user can always wrap in a container, but I suggest to use copy the innerHTML to the slotted element that we create.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4#-:-KxPdueiJYXG8UkQhNvF:b-rlq6wg)*

**Comment by manolo** [comment]
Forget about my second comment, any content works fine.
About slot, I'll propose a solution in separated PR. 
  :lgtm: 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r4, 2 of 3 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4#-:-KxRBBHHVwPfoXHAvGhu:b-bpjzy2)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 2 of 3 files at r5, 1 of 2 files at r6, 1 of 2 files at r7, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4#-:-KxRg7e0BrDVYKHZsqiv:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r7, 2 of 2 files at r8, 2 of 2 files at r9.
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/4)*

**Pull request merged**
