### PR TITLE
Fix double tab for moving out the focus. Fixes #10

### LINKED ISSUE #10: Regression: Needs push tab twice to blur
Apparently the issue was introduced in 1d34df8cf07053329df86738095eab7e91318d62

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/18)

### CODE REVIEW

**Comment by limonte** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-dropdown-menu.html, line 377 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/18#-KxlfHFAAffmFtPrBSOm:-KxlfHFAAffmFtPrBSOn:bbkf7s1) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/734927f8b23d8ac0dc20d41eeabbaa837e1a40f8/vaadin-dropdown-menu.html#L377)):*
> ```HTML
>           }
> 
>           this._nativeInput.style.opacity = this.value ? 0 : 1;
> ```

Keep in mind, that this is a breaking change from the a11y POV.

- `visibility: hidden` hide element both visually and from screen readers.
- `opacity: 0` hide element only visually, it will be still pronounced by screen readers.

Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/18)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/18#-:-KxlmQY6emHrWGykEw6M:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-dropdown-menu.html, line 377 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/18#-KxlfHFAAffmFtPrBSOm:-KxmFc_nIEISt98d3B42:b-y2nqmd) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/734927f8b23d8ac0dc20d41eeabbaa837e1a40f8/vaadin-dropdown-menu.html#L377)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Keep in mind, that this is a breaking change from the a11y POV.

- `visibility: hidden` hide element both visually and from screen readers.
- `opacity: 0` hide element only visually, it will be still pronounced by screen readers.

Not a blocker.
</blockquote></details>

Do I add some aria to the input? might be `aria-hidden` ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/18)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-dropdown-menu.html, line 377 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/18#-KxlfHFAAffmFtPrBSOm:-KxmHgfPcqhbXZiiHQA7:b-vxw0bh) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/734927f8b23d8ac0dc20d41eeabbaa837e1a40f8/vaadin-dropdown-menu.html#L377)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Do I add some aria to the input? might be `aria-hidden` ? 
</blockquote></details>

Yup, `aria-hidden="true"` will hide it from screen readers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/18)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[vaadin-dropdown-menu.html, line 377 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/18#-KxlfHFAAffmFtPrBSOm:-KxmhTylxCbYxxUdHmal:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/734927f8b23d8ac0dc20d41eeabbaa837e1a40f8/vaadin-dropdown-menu.html#L377)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Yup, `aria-hidden="true"` will hide it from screen readers.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/18)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/18#-:-Kxmj_4D_W4YTNSL3eX7:bnfp4nl)*

**Pull request merged**
