### PR TITLE
Update theme and demos

### LINKED ISSUE #94: The overlay background is invisible
https://www.dropbox.com/s/gn4uc9hkatgvuu3/Screenshot%202017-12-22%2016.41.03.png?dl=0

### PR DESCRIPTION
**Pull request by jouni**
Fixes #94 

Depends on https://github.com/vaadin/vaadin-text-field/pull/181

- Remove wrapping example (doesn’t work with Valo)

- Remove tabindex demo (not a best practice)

- Use vaadin-demo-helpers shared styles

- Fix theme to work with latest vaadin-text-field and vaadin-valo-theme
updates

- Reflect `readonly` and `label` to the internal
dropdown-menu-text-field element (the theme uses these attributes)

- Change the label default value to `undefined` (the theme needs a
non-empty string to work correctly)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dropdown-menu/93)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/vaadin-dropdown-menu.html, line 131 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93#-L0hmylal-M9bGvls9Pu:-L0hmylal-M9bGvls9Pv:bsb8hxa) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/0da4100c74f12c8ed3e8be83a99138c54254b2dd/src/vaadin-dropdown-menu.html#L131)):*
> ```HTML
>       :host {
>         display: inline-block;
>         width: 175px;
> ```

BTW removing this line breaks tests

---

*[src/vaadin-dropdown-menu.html, line 250 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93#-L0hmhkMxdh6dTOPnH35:-L0hmhkMxdh6dTOPnH36:b-u201gm) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/0ad112befe41e223d687cca6777f7e9cd01fa647/src/vaadin-dropdown-menu.html#L250)):*
> ```HTML
>             label: {
>               type: String,
>               value: undefined
> ```

the property is `undefined` by default so this line can be removed, no need to set it explicitly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93)*

**Comment by jouni** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-dropdown-menu.html, line 131 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93#-L0hmylal-M9bGvls9Pu:-L0iCU3NZJ5WkqHUjqIt:b-phb9a9) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/0da4100c74f12c8ed3e8be83a99138c54254b2dd/src/vaadin-dropdown-menu.html#L131)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW removing this line breaks tests
</blockquote></details>

Fixed the one test that was failing because of this. The other failing test is something else, it doesn’t work in master either.

---

*[src/vaadin-dropdown-menu.html, line 250 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93#-L0hmhkMxdh6dTOPnH35:-L0iCZSQw2ySpyaCBuGI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/0ad112befe41e223d687cca6777f7e9cd01fa647/src/vaadin-dropdown-menu.html#L250)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

the property is `undefined` by default so this line can be removed, no need to set it explicitly
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93)*

**Comment by jouni** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-dropdown-menu.html, line 131 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93#-L0hmylal-M9bGvls9Pu:-L0iGGJQ0qPaQ3mh8ZdM:b-ysqgps) ([raw file](https://github.com/vaadin/vaadin-dropdown-menu/blob/0da4100c74f12c8ed3e8be83a99138c54254b2dd/src/vaadin-dropdown-menu.html#L131)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Fixed the one test that was failing because of this. The other failing test is something else, it doesn’t work in master either.
</blockquote></details>

Fixed the other test with Tomi. The build should pass now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93)*

**Comment by jouni** [comment]
Hmm, strange. Tests seemed to be passing at least locally.

**Comment by jouni** [comment]
@manolo, could you take a look at the test that is failing on Win10 IE11? 
> `expected undefined to be 1`
https://github.com/vaadin/vaadin-dropdown-menu/blob/master/test/dropdown-menu-test.html#L129

**Comment by jouni** [comment]
:lgtm: 

Thanks for fixing the tests @web-padawan (I also forgot, again, that Manolo is working in another project at the moment).

---

Review status: 1 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93#-:-L0zqIZ_vl1CIrrECY40:bqjfu9i)*

**Comment by web-padawan** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93)*

**Comment by web-padawan** [comment]
One test was failing in iPhone and iPad due to the [resize event bug](https://bugs.webkit.org/show_bug.cgi?id=170595) introduced in iOS 10.3. But anyways, that test covers logic handled by the `<iron-media-query>` which in turn uses `window.matchMedia` API. So this is not a part of the element logic and therefore we can skip it and go ahead.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93#-:-L1JEBwgYYCOx2KskTOY:b7jd3e1)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93#-:-L1JFfYU8kk2FXfCfwIU:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-dropdown-menu/93#-:-L1M70Ylvg1xsbfRKy_E:bnfp4nl)*

**Pull request merged**
